eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/demo/eureka/
server:
  port: 8762
  servlet:
    context-path: /demo
spring:
  application:
    #    此处名称最好写项目名称，便于识别服务提供者
    name: eureka-client-01
