eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #检索服务(从注册中心获取服务)
    fetch-registry: true
    #如果有多个注册中心,需要配置其他的路径,用逗号隔离
    serviceUrl:
      defaultZone: http://localhost:8761/demo/eureka/
  instance:
    #将IP注册到eureka中，如果为false默认注册主机名
    prefer-ip-address: true



server:
  port: 8762
  servlet:
    context-path: /demo
spring:
  application:
    #    此处名称最好写项目名称，便于识别服务提供者
    name: eureka-client-01


resourceYml:
  path: my-config.yml , my-config-02.yml